"""initial database migration

Revision ID: 3184ecc632e3
Revises:
Create Date: 2021-04-03 18:05:24.850379

"""
from alembic import op
import sqlalchemy as sa
import csv
import datetime

# revision identifiers, used by Alembic.
revision = '3184ecc632e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    techs = op.create_table('Technologies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    countries = op.create_table('countries_cities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('province', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    users = op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('register_on', sa.DateTime(), nullable=False),
    sa.Column('last_pass_change', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('surname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('country_city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_city_id'], ['countries_cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('other_webpage', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=False),
    sa.Column('github', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bio')
    )
    # ### end Alembic commands ###

    admin_user = [{'user_id': 'admin',
                  'password_hash': "$2b$12$L1Glnc6IiLezG2J4.hdNJ.DONz2rIWX0V.P98wLUQXH120pci1YP2",
                  "register_on": datetime.datetime(2021, 1, 1),
                  "last_pass_change": datetime.datetime(2021, 1, 1),
                  "name": 'admin',
                  "surname": 'admin',
                  "email": 'admin@admin.com',
                  "country_city_id": 1
                  }]
    op.bulk_insert(users, admin_user)

    with open('worldcities.csv', 'r') as f:
        reader = csv.DictReader(f)
        country_list = [row for row in reader]

    op.bulk_insert(
        countries,
        country_list
    )

    with open('lang.csv', 'r') as f:
        reader = csv.DictReader(f)
        langs = [row for row in reader]

    op.bulk_insert(
        techs,
        langs
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate')
    op.drop_table('users')
    op.drop_table('countries_cities')
    op.drop_table('Technologies')
    # ### end Alembic commands ###
